In [ ]:
!pip install awscli

In [5]:
!aws s3 cp s3://recommendation-system-1149/raw-data/sample_data/articles_sample.parquet ./data
!echo "articles data downloaded"
!aws s3 cp s3://recommendation-system-1149/raw-data/sample_data/customers_sample.parquet ./data
!echo "customer data downloaded"
!aws s3 cp s3://recommendation-system-1149/raw-data/sample_data/transactions_sample.parquet ./data
!echo "transactions data downloaded"

download: s3://recommendation-system-1149/raw-data/sample_data/articles_sample.parquet to data/articles_sample.parquet
articles data downloaded
download: s3://recommendation-system-1149/raw-data/sample_data/customers_sample.parquet to data/customers_sample.parquet
customer data downloaded
download: s3://recommendation-system-1149/raw-data/sample_data/transactions_sample.parquet to data/transactions_sample.parquet
transactions data downloaded

In [3]:
print('all ok')

all ok

In [4]:
import pandas as pd

In [ ]:
article= pd.read_parquet('sample_data/articles_sample.parquet')
customer= pd.read_parquet('sample_data/customers_sample.parquet')
transaction= pd.read_parquet('sample_data/transactions_sample.parquet')

In [8]:
article.head()

,article_id,product_code,prod_name,product_type_no,product_type_name,product_group_name,graphical_appearance_no,graphical_appearance_name,colour_group_code,colour_group_name,...,department_name,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc
0,108775015,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,9,Black,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
1,108775044,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,10,White,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
2,110065001,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,9,Black,...,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."
3,110065002,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,10,White,...,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."
4,110065011,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,12,Light Beige,...,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."

In [9]:
article.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34709 entries, 0 to 34708
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   article_id                    34709 non-null  int64
 1   product_code                  34709 non-null  int64
 2   prod_name                     34709 non-null  object
 3   product_type_no               34709 non-null  int64
 4   product_type_name             34709 non-null  object
 5   product_group_name            34709 non-null  object
 6   graphical_appearance_no       34709 non-null  int64
 7   graphical_appearance_name     34709 non-null  object
 8   colour_group_code             34709 non-null  int64
 9   colour_group_name             34709 non-null  object
 10  perceived_colour_value_id     34709 non-null  int64
 11  perceived_colour_value_name   34709 non-null  object
 12  perceived_colour_master_id    34709 non-null  int64
 13  perceived_colour_master_name  34709 non-null  object
 14  department_no                 34709 non-null  int64
 15  department_name               34709 non-null  object
 16  index_code                    34709 non-null  object
 17  index_name                    34709 non-null  object
 18  index_group_no                34709 non-null  int64
 19  index_group_name              34709 non-null  object
 20  section_no                    34709 non-null  int64
 21  section_name                  34709 non-null  object
 22  garment_group_no              34709 non-null  int64
 23  garment_group_name            34709 non-null  object
 24  detail_desc                   34587 non-null  object
dtypes: int64(11), object(14)
memory usage: 6.6+ MB

In [21]:
article.shape

(34709, 25)

In [34]:
no_need =['article_id', 'product_code']
vals={}
for el in article.columns:
    if el in no_need : 
        continue
    else :
        vals[el]=len(article[el].unique())

In [35]:
print(vals)

{'prod_name': 18375, 'product_type_no': 110, 'product_type_name': 109, 'product_group_name': 16, 'graphical_appearance_no': 30, 'graphical_appearance_name': 30, 'colour_group_code': 49, 'colour_group_name': 49, 'perceived_colour_value_id': 8, 'perceived_colour_value_name': 8, 'perceived_colour_master_id': 20, 'perceived_colour_master_name': 20, 'department_no': 288, 'department_name': 239, 'index_code': 10, 'index_name': 10, 'index_group_no': 5, 'index_group_name': 5, 'section_no': 57, 'section_name': 56, 'garment_group_no': 21, 'garment_group_name': 21, 'detail_desc': 17283}

In [13]:
customer.head()

,customer_id,FN,Active,club_member_status,fashion_news_frequency,age,postal_code
0,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,1.0,1.0,ACTIVE,Regularly,52.0,25fa5ddee9aac01b35208d01736e57942317d756b32ddd...
1,00007d2de826758b65a93dd24ce629ed66842531df6699...,1.0,1.0,ACTIVE,Regularly,32.0,8d6f45050876d059c830a0fe63f1a4c022de279bb68ce3...
2,0000f1c71aafe5963c3d195cf273f7bfd50bbf17761c91...,1.0,1.0,ACTIVE,Regularly,30.0,7c902dca60ee0bd0f9030eefd445d11146e8d24835738a...
3,0001ab2ebc1bb9a21d135e2fefdb11f12bee5c74ab2984...,NaN,NaN,ACTIVE,NONE,48.0,34b0763df8e56ebfc6cc5a33bf251da31e2705b6fe106d...
4,0001d44dbe7f6c4b35200abdb052c77a87596fe1bdcc37...,1.0,1.0,ACTIVE,Regularly,44.0,930b19ae7db8abb5a27f4da10217755a7305b4c452f5e0...

In [38]:
customer.columns

Index(['customer_id', 'FN', 'Active', 'club_member_status',
       'fashion_news_frequency', 'age', 'postal_code'],
      dtype='object')

In [36]:
transaction.head()

,t_dat,customer_id,article_id,price,sales_channel_id
0,2019-09-13,215895f90002eb3d1a04bd603513c8e85e6002ef08f136...,786586001,0.022017,1
1,2019-02-23,7b183268e3a4623b80d5325ec4a20a0af0edff7bcb1748...,658911001,0.028797,2
2,2019-07-17,2eb7412239a90c0570cd3d1bf0492856ae5b59058b1ea6...,759326005,0.050831,2
3,2019-05-16,74f162e5a170fd57207aa2a7d5c58479ee9de903b2a277...,737137004,0.027102,1
4,2019-08-10,aab9306ee28c4db494003955f80355e540b01480ab35cf...,785931001,0.050831,2

In [ ]:
df=transaction.merge(
    right=customer[['customer_id', 'FN', 'Active', 'club_member_status','fashion_news_frequency', 'age', 'postal_code']],
    on='customer_id'
).groupby('customer_id').agg(
    total_sales=('price','sum'),
    avg_sales=('price','mean'),
    total_orders=('price','count')
).reset_index()

In [50]:
df.head()

,t_dat,customer_id,article_id,price,sales_channel_id,FN,Active,club_member_status,fashion_news_frequency,age,postal_code
0,2019-09-13,215895f90002eb3d1a04bd603513c8e85e6002ef08f136...,786586001,0.022017,1,NaN,NaN,ACTIVE,NONE,41.0,535a8924d2fed347afdb2893ddf697f837d6c0703cd272...
1,2019-02-23,7b183268e3a4623b80d5325ec4a20a0af0edff7bcb1748...,658911001,0.028797,2,1.0,1.0,ACTIVE,Regularly,30.0,22bef17153b987897b5a153ada01111464a522afa3ea95...
2,2019-07-17,2eb7412239a90c0570cd3d1bf0492856ae5b59058b1ea6...,759326005,0.050831,2,1.0,1.0,ACTIVE,Regularly,22.0,c7c22c9d2b5f95048da10aa1bd0e618d885da11a274988...
3,2019-05-16,74f162e5a170fd57207aa2a7d5c58479ee9de903b2a277...,737137004,0.027102,1,NaN,NaN,ACTIVE,NONE,21.0,65f32e7b3a69147d566c4de5fad1edec43b002f57be4cb...
4,2019-08-10,aab9306ee28c4db494003955f80355e540b01480ab35cf...,785931001,0.050831,2,1.0,1.0,ACTIVE,Regularly,49.0,8bbedd51d93d24d5837f0690ad1d4e129cb93d1384b4b7...
...,...,...,...,...,...,...,...,...,...,...,...
99995,2019-02-25,45a7956b5a824f851380d9b0f0b5eb4ecbedf10ce03f09...,214844001,0.003373,1,NaN,NaN,ACTIVE,NONE,24.0,265016b0a203003f2f216e5eee17e59e911084b0f2bbac...
99996,2020-03-05,1dc6a15c8c2e4c68fdcaa5edcb32ae5b8b56948ffb2308...,689365049,0.015237,2,NaN,NaN,ACTIVE,NONE,32.0,7422b8ac21c3d8374fcc916481e310310c538fa89642a7...
99997,2019-06-03,583fb775ac2b4fcda103eee851fbb712c17fa1534ca24d...,653188002,0.011169,1,1.0,1.0,ACTIVE,Regularly,22.0,c80e9e879c7b54cb644d47afaaec3947e8104e71ee68c1...
99998,2020-04-10,6d1ed179b62057d4ae8cbf1d9ac3dbb9512d3f5a4af949...,879294001,0.025407,2,NaN,NaN,ACTIVE,NONE,47.0,491cd20f4d08cc73ad2aa73dde97bba0c9791442db2ab6...
99999,2019-05-03,add481698e90befd807d4d291fbd4c2cfd2d4c15d04599...,700329006,0.033881,2,NaN,NaN,ACTIVE,NONE,25.0,cbd4ee37c9fd26bf0bbdbd419452b982269eba981cc762...