In [1]:
print("all OK ")

all OK

In [2]:
import pandas as pd 
import pyarrow

In [3]:
item_features=pd.read_parquet(
    path="s3://recommendation-system-1149/processed/test/train/item_features/",
    engine="pyarrow"
)

In [4]:
item_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28907 entries, 0 to 28906
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   article_id            28907 non-null  object
 1   item_purchase_count   28907 non-null  int64
 2   unique_buyers         28907 non-null  int64
 3   avg_item_price        28907 non-null  float64
 4   department_no         28907 non-null  int64
 5   product_type_no       28907 non-null  int64
 6   section_no            28907 non-null  int64
 7   garment_group_no      28907 non-null  int64
 8   colour_group_code     28907 non-null  int64
 9   index_group_no        28907 non-null  int64
 10  days_since_last_sale  28907 non-null  int32
 11  image_embedding       28821 non-null  object
 12  embedding_available   28907 non-null  int32
dtypes: float64(1), int32(2), int64(8), object(2)
memory usage: 2.6+ MB

In [5]:
item_features.head()

,article_id,item_purchase_count,unique_buyers,avg_item_price,department_no,product_type_no,section_no,garment_group_no,colour_group_code,index_group_no,days_since_last_sale,image_embedding,embedding_available
0,0696542001,9,9,0.022243,1510,258,6,1010,73,1,262,"[-0.025406942, 0.0070250137, 0.0013820805, 0.0...",1
1,0767820002,1,1,0.047441,1322,265,15,1013,13,1,388,"[-0.031788614, 0.019962028, -0.0060859798, 0.0...",1
2,0785665002,3,3,0.040944,1616,252,11,1003,93,1,162,"[0.005776446, -0.00014068311, 0.031417087, -0....",1
3,0755604001,2,2,0.010576,3527,91,64,1020,9,1,241,"[-0.037646007, -0.02196367, 0.023778664, 0.026...",1
4,0623059004,2,2,0.014390,1338,306,61,1017,9,1,161,"[0.010669624, -0.030550204, 0.003498738, -0.00...",1

In [6]:
ranking_features=pd.read_parquet(
    path="s3://recommendation-system-1149/processed/prod/train/ranking_features/",
    engine="pyarrow"
)

In [7]:
ranking_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22585390 entries, 0 to 22585389
Data columns (total 15 columns):
 #   Column                 Dtype
---  ------                 -----
 0   customer_id            object
 1   article_id             object
 2   embedding_available    int32
 3   purchase_count         int64
 4   avg_spend              float64
 5   category_diversity     int64
 6   avg_purchase_gap_days  float64
 7   item_purchase_count    int64
 8   avg_item_price         float64
 9   days_since_last_sale   int32
 10  price_affinity         float64
 11  sales_channel_id       int64
 12  day_of_week            int32
 13  month                  int32
 14  is_weekend             int32
dtypes: float64(4), int32(5), int64(4), object(2)
memory usage: 2.1+ GB

In [8]:
ranking_features.head(-4)

,customer_id,article_id,embedding_available,purchase_count,avg_spend,category_diversity,avg_purchase_gap_days,item_purchase_count,avg_item_price,days_since_last_sale,price_affinity,sales_channel_id,day_of_week,month,is_weekend
0,6fc69d4f0ad86cf7cea4eab3685d20bfbe5b61c8b94041...,0564787018,0,59,0.031921,6,6.413793,1216,0.029915,164,0.937159,2,2,12,0
1,028b7dbd8accfd9e3a42cfbc1146c1935191368767187d...,0697054054,0,35,0.027102,5,14.970588,1764,0.023345,54,0.861358,1,7,9,1
2,4d6d81251b5e6d99248fbd636696c379ba8721c338d6fa...,0816737002,0,92,0.046240,2,5.648352,333,0.048170,1,1.041756,2,4,3,0
3,9bd4f445dce997c841a93df8d541833d86e466f41d8620...,0576692001,1,61,0.020616,8,8.500000,902,0.015333,1,0.743734,2,7,8,1
4,8fbf411ac749acf59f0fcc5fea8ed631de825afb9393ad...,0772176003,0,54,0.028137,7,9.169811,884,0.030988,0,1.101290,2,7,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22585381,0376418babe8c42b7aa9835638f98e65b1ca16c615a391...,0465655019,1,27,0.027070,6,17.923077,3584,0.015176,2,0.560614,2,6,7,0
22585382,1c4915915046a3a7e84070db8662683f8ea41d44e3c285...,0783346021,0,127,0.028997,5,4.222222,599,0.024008,0,0.827940,2,1,4,1
22585383,8f0f23f922d7ae9a97e17c9a2b81d51d9d5cdba126a017...,0370594018,1,37,0.028998,5,7.777778,784,0.012296,54,0.424025,2,2,4,0
22585384,6b40594d15b51ef92f5915b22c6460868528fc678d6455...,0372860062,1,42,0.027828,4,9.292683,1254,0.011322,48,0.406872,1,7,3,1
22585385,ed5358acfbaab4ed9799806e686da30abda4d5e03e33eb...,0648769001,0,132,0.026997,8,4.183206,1030,0.015687,1,0.581058,2,1,7,1

In [37]:
two_tower_interaction=pd.read_parquet(
    path="s3://recommendation-system-1149/processed/test/train/two_tower_interactions/",
    engine="pyarrow"
)

In [40]:
two_tower_interaction.head()

,customer_id,article_id,t_dat,price,sales_channel_id,event_timestamp,FN,Active,club_member_status,fashion_news_frequency,...,year,is_weekend,purchase_count,avg_spend,favorite_category,last_purchase,item_purchase_count,unique_buyers,avg_item_price,favorite_color
0,ead8e6f06b564e64c704d42b9df3318e2f72c88a6c8583...,0628926003,2019-01-28,0.020322,2,2019-01-28,1.0,1.0,active,none,...,2019,0,1,0.020322,garment upper body,2019-01-28,3,3,0.012412,black
1,e17d5f65f0be6f1fe1c4b376713924c626a3b265f4fa64...,0240561001,2019-10-28,0.012102,1,2019-10-28,1.0,1.0,active,none,...,2019,0,1,0.012102,socks & tights,2019-10-28,18,18,0.012126,black
2,87dea9d47f905e69b6b5bbca3752952c8b91209df9f3e4...,0814131001,2020-01-23,0.015322,1,2020-01-23,1.0,1.0,active,none,...,2020,0,1,0.015322,accessories,2020-01-23,4,4,0.015258,gold
3,6989f77b0938a14a7b929a40978dc0081708da5e101e18...,0748141003,2019-06-22,0.023153,1,2019-06-22,1.0,1.0,active,none,...,2019,1,1,0.023153,garment lower body,2019-06-22,3,3,0.022395,black
4,7230ffc5f0b3d465b9a8148988762c4d41c3db034ceb79...,0844727001,2020-02-10,0.042356,2,2020-02-10,1.0,1.0,active,none,...,2020,0,1,0.042356,garment upper body,2020-02-10,2,2,0.039534,black

In [39]:
two_tower_interaction["article_id"] = (
    two_tower_interaction["article_id"]
    .astype(str)
    .str.zfill(10)
)

In [41]:
import pyarrow as pa
import pyarrow.dataset as ds

table = pa.Table.from_pandas(
    two_tower_interaction,
    preserve_index=False
)

In [ ]:
import s3fs
fs=s3fs.S3FileSystem()
import pyarrow as pa
import pyarrow.dataset as ds

table = pa.Table.from_pandas(
    two_tower_interaction,
    preserve_index=False
)
ds.write_dataset(
    table,
    base_dir="s3://recommendation-system-1149/processed/test/train/two_tower_interactions/",
    format="parquet",
    filesystem=fs,
    existing_data_behavior="delete_matching"
)
two_tower_interaction_fixed=pd.read_parquet(
    path="s3://recommendation-system-1149/processed/test/train/two_tower_interactions/",
    engine="pyarrow"
)

In [45]:
two_tower_interaction_fixed.head()

,customer_id,article_id,t_dat,price,sales_channel_id,event_timestamp,FN,Active,club_member_status,fashion_news_frequency,...,year,is_weekend,purchase_count,avg_spend,favorite_category,last_purchase,item_purchase_count,unique_buyers,avg_item_price,favorite_color
0,ead8e6f06b564e64c704d42b9df3318e2f72c88a6c8583...,0628926003,2019-01-28,0.020322,2,2019-01-28,1.0,1.0,active,none,...,2019,0,1,0.020322,garment upper body,2019-01-28,3,3,0.012412,black
1,e17d5f65f0be6f1fe1c4b376713924c626a3b265f4fa64...,0240561001,2019-10-28,0.012102,1,2019-10-28,1.0,1.0,active,none,...,2019,0,1,0.012102,socks & tights,2019-10-28,18,18,0.012126,black
2,87dea9d47f905e69b6b5bbca3752952c8b91209df9f3e4...,0814131001,2020-01-23,0.015322,1,2020-01-23,1.0,1.0,active,none,...,2020,0,1,0.015322,accessories,2020-01-23,4,4,0.015258,gold
3,6989f77b0938a14a7b929a40978dc0081708da5e101e18...,0748141003,2019-06-22,0.023153,1,2019-06-22,1.0,1.0,active,none,...,2019,1,1,0.023153,garment lower body,2019-06-22,3,3,0.022395,black
4,7230ffc5f0b3d465b9a8148988762c4d41c3db034ceb79...,0844727001,2020-02-10,0.042356,2,2020-02-10,1.0,1.0,active,none,...,2020,0,1,0.042356,garment upper body,2020-02-10,2,2,0.039534,black

In [46]:
ranking_interactions=pd.read_parquet(
    path="s3://recommendation-system-1149/processed/test/train/ranking_interactions/",
    engine="pyarrow"
)

In [47]:
ranking_interactions.head()

,article_id,customer_id,t_dat,price,sales_channel_id,event_timestamp,FN,Active,club_member_status,fashion_news_frequency,...,unique_buyers,day_of_week,month,year,is_weekend,price_affinity,popularity_price_score,last_purchase_ts,days_since_last_purchase,label
0,756898001,7b5b24d5af565d0a43101bdaceb35a284ae454adf39f60...,2019-06-14,0.050831,2,2019-06-14,1.0,1.0,active,none,...,3,6,6,2019,0,0.000000,0.152492,2019-06-14,0,1
1,733348001,4cf7ac03964e3c3dd6e8c1b5d14883a1be1905ff95a62a...,2019-07-27,0.030169,2,2019-07-27,1.0,1.0,active,regularly,...,6,7,7,2019,1,0.008689,0.181017,2020-07-12,351,1
2,718747002,45d1ce28c137d4f0f52aea7b95a31f59083a5a89456e35...,2019-11-09,0.042356,2,2019-11-09,1.0,1.0,active,none,...,3,7,11,2019,1,0.008475,0.127068,2019-11-09,0,1
3,585158003,3adbe6fedf82cbcbb1f77fa11dc9c3795b692207d42c33...,2019-07-01,0.015627,1,2019-07-01,1.0,1.0,active,regularly,...,14,2,7,2019,0,0.004890,0.218780,2019-07-01,0,1
4,516951003,502b5016838f7505bb1ba14edd2363396bdd92134eced6...,2019-09-28,0.020322,2,2019-09-28,1.0,1.0,active,regularly,...,3,7,9,2019,1,0.002542,0.060966,2019-09-28,0,1

In [48]:
ranking_interactions["article_id"] = (
    two_tower_interaction["article_id"]
    .astype(str)
    .str.zfill(10)
)

In [49]:
import s3fs
fs=s3fs.S3FileSystem()
import pyarrow as pa
import pyarrow.dataset as ds

table = pa.Table.from_pandas(
    ranking_interactions,
    preserve_index=False
)
ds.write_dataset(
    table,
    base_dir="s3://recommendation-system-1149/processed/test/train/ranking_interactions/",
    format="parquet",
    filesystem=fs,
    existing_data_behavior="delete_matching"
)

In [50]:
ranking_interactions_fixed=pd.read_parquet(
    path="s3://recommendation-system-1149/processed/test/train/ranking_interactions/",
    engine="pyarrow"
)

In [51]:
ranking_interactions_fixed.head()

,article_id,customer_id,t_dat,price,sales_channel_id,event_timestamp,FN,Active,club_member_status,fashion_news_frequency,...,unique_buyers,day_of_week,month,year,is_weekend,price_affinity,popularity_price_score,last_purchase_ts,days_since_last_purchase,label
0,0628926003,7b5b24d5af565d0a43101bdaceb35a284ae454adf39f60...,2019-06-14,0.050831,2,2019-06-14,1.0,1.0,active,none,...,3,6,6,2019,0,0.000000,0.152492,2019-06-14,0,1
1,0240561001,4cf7ac03964e3c3dd6e8c1b5d14883a1be1905ff95a62a...,2019-07-27,0.030169,2,2019-07-27,1.0,1.0,active,regularly,...,6,7,7,2019,1,0.008689,0.181017,2020-07-12,351,1
2,0814131001,45d1ce28c137d4f0f52aea7b95a31f59083a5a89456e35...,2019-11-09,0.042356,2,2019-11-09,1.0,1.0,active,none,...,3,7,11,2019,1,0.008475,0.127068,2019-11-09,0,1
3,0748141003,3adbe6fedf82cbcbb1f77fa11dc9c3795b692207d42c33...,2019-07-01,0.015627,1,2019-07-01,1.0,1.0,active,regularly,...,14,2,7,2019,0,0.004890,0.218780,2019-07-01,0,1
4,0844727001,502b5016838f7505bb1ba14edd2363396bdd92134eced6...,2019-09-28,0.020322,2,2019-09-28,1.0,1.0,active,regularly,...,3,7,9,2019,1,0.002542,0.060966,2019-09-28,0,1

In [52]:
embeddings=pd.read_parquet(
    path="s3://recommendation-system-1149/features/sample/embeddings/",
    engine='pyarrow'
)

In [53]:
embeddings.head()

,article_id,image_embedding,event_timestamp
0,0915449001,"[-0.023404045, -0.021279886, 0.023290839, -0.0...",2026-06-01 13:49:01.268397
1,0649439001,"[-0.026924625, 0.008277589, 0.011145024, 0.014...",2026-06-01 13:49:01.268430
2,0768939005,"[0.0038587956, -0.0031747057, 0.07870311, -0.0...",2026-06-01 13:49:01.268443
3,0357751003,"[-0.052767415, -0.023114525, 0.050868757, -0.0...",2026-06-01 13:49:01.268453
4,0829439002,"[0.0116912, 0.024975896, 0.015518011, 0.035798...",2026-06-01 13:49:01.268464

In [29]:
embeddings=pd.read_parquet(
    path="s3://recommendation-system-1149/features/main/embeddings/",
    engine='pyarrow'
)

In [30]:
embeddings.head()

,article_id,image_embedding,event_timestamp
0,0108775015,"[-0.0084804995, 0.0048310226, 0.016563838, 0.0...",2026-06-01 14:06:09.363009
1,0108775044,"[-0.027783174, 0.0031375962, 0.01607018, 0.031...",2026-06-01 14:06:09.363032
2,0108775051,"[-0.030256057, 0.006075923, 0.00521416, 0.0054...",2026-06-01 14:06:09.363046
3,0203027045,"[-0.008440828, 0.02568077, -0.006446446, 0.015...",2026-06-01 14:06:28.046053
4,0201219011,"[-0.037752114, 0.013903375, 0.019218147, 0.043...",2026-06-01 14:06:28.046075